name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  REACT_APP_API_URL: https://api-dev.pyrypajunpaa.com/history
  REACT_APP_CDN_URL: http://cdn-dev.pyrypajunpaa.com
  REACT_APP_USER_POOL_ID: eu-central-1_qfPL1nsJ9
  REACT_APP_CLIENT_ID: 48ihri52osnjs1d69p2jp59d18
  REACT_APP_AWS_REGION: eu-central-1

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true